version: '3'

services:
  db:
    container_name: 'crypto_web_db'
    image: 'postgres:15'
    restart: on-failure
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
  cache:
    container_name: 'redis_cache'
    image: 'redis:7.0.9'
    restart: on-failure
    ports:
      - "6379:6379"

volumes:
  db-data:

