"""empty message

Revision ID: 00dd51555e14
Revises: f5a78dbc58bc
Create Date: 2023-02-18 12:05:30.661579

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "00dd51555e14"
down_revision = "f5a78dbc58bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("time_label", sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "time_label")
    # ### end Alembic commands ###
